# Generated by Django 4.1.7 on 2023-03-21 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_rename_author_id_ad_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='category_id',
            new_name='category',
        ),
    ]
