# Generated by Django 4.1.7 on 2023-03-27 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_rename_category_id_ad_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
